#You can fill in the following translator: bing, google, baidu
#Allowed Values: BING, GOOGLE, BAIDU
translator = "BING"
#You can fill in the following language:
# af (Afrikaans)					sq (Albanian)					am (Amharic)
# ar (Arabic)						hy (Armenian)					as (Assamese)
# az (Azerbaijani)					bn (Bangla)						ba (Bashkir)
# eu (Basque)						bs (Bosnian)					bg (Bulgarian)
# yue (Cantonese (Traditional))		ca (Catalan)					lzh (Chinese (Literary))
# zh-Hans (Chinese Simplified)		zh-Hant (Chinese Traditional)	hr (Croatian)
# cs (Czech)						da (Danish)						prs (Dari)
# dv (Divehi)						nl (Dutch)						en (English)
# et (Estonian)						fo (Faroese)					fj (Fijian)
# fil (Filipino)					fi (Finnish)					fr (French)
# fr-CA (French (Canada))			gl (Galician)					lug (Ganda)
# ka (Georgian)						de (German)						el (Greek)
# gu (Gujarati)						ht (Haitian Creole)				ha (Hausa)
# he (Hebrew)						hi (Hindi)						mww (Hmong Daw)
# hu (Hungarian)					is (Icelandic)					ig (Igbo)
# id (Indonesian)					ikt (Inuinnaqtun)				iu (Inuktitut)
# iu-Latn (Inuktitut (Latin))		ga (Irish)						it (Italian)
# ja (Japanese)						kn (Kannada)					kk (Kazakh)
# km (Khmer)						rw (Kinyarwanda)				tlh-Latn (Klingon (Latin))
# gom (Konkani)						ko (Korean)						ku (Kurdish (Central))
# kmr (Kurdish (Northern))			ky (Kyrgyz)						lo (Lao)
# lv (Latvian)						ln (Lingala)					lt (Lithuanian)
# dsb (Lower Sorbian)				mk (Macedonian)					mai (Maithili)
# mg (Malagasy)						ms (Malay)						ml (Malayalam)
# mt (Maltese)						mr (Marathi)					mn-Cyrl (Mongolian (Cyrillic))
# mn-Mong (Mongolian (Traditional))	my (Myanmar (Burmese))			mi (Māori)
# ne (Nepali)						nb (Norwegian)					nya (Nyanja)
# or (Odia)							ps (Pashto)						fa (Persian)
# pl (Polish)						pt (Portuguese (Brazil))		pt-PT (Portuguese (Portugal))
# pa (Punjabi)						otq (Querétaro Otomi)			ro (Romanian)
# run (Rundi)						ru (Russian)					sm (Samoan)
# sr-Cyrl (Serbian (Cyrillic))		sr-Latn (Serbian (Latin))		st (Sesotho)
# nso (Sesotho sa Leboa)			tn (Setswana)					sn (Shona)
# sd (Sindhi)						si (Sinhala)					sk (Slovak)
# sl (Slovenian)					so (Somali)						es (Spanish)
# sw (Swahili)						sv (Swedish)					ty (Tahitian)
# ta (Tamil)						tt (Tatar)						te (Telugu)
# th (Thai)							bo (Tibetan)					ti (Tigrinya)
# to (Tongan)						tr (Turkish)					tk (Turkmen)
# uk (Ukrainian)					hsb (Upper Sorbian)				ur (Urdu)
# ug (Uyghur)						uz (Uzbek (Latin))				vi (Vietnamese)
# cy (Welsh)						xh (Xhosa)						yo (Yoruba)
# yua (Yucatec Maya)				zu (Zulu)
#
# auto (Auto Detect)
#
#Allowed Values: AUTO_DETECT, AFRIKAANS, ALBANIAN, AMHARIC, ARABIC, ARMENIAN, ASSAMESE, AZERBAIJANI, BANGLA, BASHKIR, BASQUE, BOSNIAN, BULGARIAN, CANTONESE_TRADITIONAL, CATALAN, CHINESE_LITERARY, CHINESE_SIMPLIFIED, CHINESE_TRADITIONAL, CROATIAN, CZECH, DANISH, DARI, DIVEHI, DUTCH, ENGLISH, ESTONIAN, FAROESE, FIJIAN, FILIPINO, FINNISH, FRENCH, FRENCH_CANADA, GALICIAN, GANDA, GEORGIAN, GERMAN, GREEK, GUJARATI, HAITIAN_CREOLE, HAUSA, HEBREW, HINDI, HMONG_DAW, HUNGARIAN, ICELANDIC, IGBO, INDONESIAN, INUINNAQTUN, INUKTITUT, INUKTITUT_LATIN, IRISH, ITALIAN, JAPANESE, KANNADA, KAZAKH, KHMER, KINYARWANDA, KLINGON_LATIN, KONKANI, KOREAN, KURDISH_CENTRAL, KURDISH_NORTHERN, KYRGYZ, LAO, LATVIAN, LINGALA, LITHUANIAN, LOWER_SORBIAN, MACEDONIAN, MAITHILI, MALAGASY, MALAY, MALAYALAM, MALTESE, MARATHI, MONGOLIAN_CYRILLIC, MONGOLIAN_TRADITIONAL, MYANMAR_BURMESE, MĀORI, NEPALI, NORWEGIAN, NYANJA, ODIA, PASHTO, PERSIAN, POLISH, PORTUGUESE_BRAZIL, PORTUGUESE_PORTUGAL, PUNJABI, QUERÉTARO_OTOMI, ROMANIAN, RUNDI, RUSSIAN, SAMOAN, SERBIAN_CYRILLIC, SERBIAN_LATIN, SESOTHO, SESOTHO_SA_LEBOA, SETSWANA, SHONA, SINDHI, SINHALA, SLOVAK, SLOVENIAN, SOMALI, SPANISH, SWAHILI, SWEDISH, TAHITIAN, TAMIL, TATAR, TELUGU, THAI, TIBETAN, TIGRINYA, TONGAN, TURKISH, TURKMEN, UKRAINIAN, UPPER_SORBIAN, URDU, UYGHUR, UZBEK_LATIN, VIETNAMESE, WELSH, XHOSA, YORUBA, YUCATEC_MAYA, ZULU
lang-from = "AUTO_DETECT"
#You can fill in the same language as above, except for "auto"
#Allowed Values: AUTO_DETECT, AFRIKAANS, ALBANIAN, AMHARIC, ARABIC, ARMENIAN, ASSAMESE, AZERBAIJANI, BANGLA, BASHKIR, BASQUE, BOSNIAN, BULGARIAN, CANTONESE_TRADITIONAL, CATALAN, CHINESE_LITERARY, CHINESE_SIMPLIFIED, CHINESE_TRADITIONAL, CROATIAN, CZECH, DANISH, DARI, DIVEHI, DUTCH, ENGLISH, ESTONIAN, FAROESE, FIJIAN, FILIPINO, FINNISH, FRENCH, FRENCH_CANADA, GALICIAN, GANDA, GEORGIAN, GERMAN, GREEK, GUJARATI, HAITIAN_CREOLE, HAUSA, HEBREW, HINDI, HMONG_DAW, HUNGARIAN, ICELANDIC, IGBO, INDONESIAN, INUINNAQTUN, INUKTITUT, INUKTITUT_LATIN, IRISH, ITALIAN, JAPANESE, KANNADA, KAZAKH, KHMER, KINYARWANDA, KLINGON_LATIN, KONKANI, KOREAN, KURDISH_CENTRAL, KURDISH_NORTHERN, KYRGYZ, LAO, LATVIAN, LINGALA, LITHUANIAN, LOWER_SORBIAN, MACEDONIAN, MAITHILI, MALAGASY, MALAY, MALAYALAM, MALTESE, MARATHI, MONGOLIAN_CYRILLIC, MONGOLIAN_TRADITIONAL, MYANMAR_BURMESE, MĀORI, NEPALI, NORWEGIAN, NYANJA, ODIA, PASHTO, PERSIAN, POLISH, PORTUGUESE_BRAZIL, PORTUGUESE_PORTUGAL, PUNJABI, QUERÉTARO_OTOMI, ROMANIAN, RUNDI, RUSSIAN, SAMOAN, SERBIAN_CYRILLIC, SERBIAN_LATIN, SESOTHO, SESOTHO_SA_LEBOA, SETSWANA, SHONA, SINDHI, SINHALA, SLOVAK, SLOVENIAN, SOMALI, SPANISH, SWAHILI, SWEDISH, TAHITIAN, TAMIL, TATAR, TELUGU, THAI, TIBETAN, TIGRINYA, TONGAN, TURKISH, TURKMEN, UKRAINIAN, UPPER_SORBIAN, URDU, UYGHUR, UZBEK_LATIN, VIETNAMESE, WELSH, XHOSA, YORUBA, YUCATEC_MAYA, ZULU
lang-to = "CHINESE_SIMPLIFIED"

